eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: HelloService1
        #uri: http://localhost:8088/
        uri: lb://service1
        predicates:
        - Path=/helloservice1/**
        #filters:
        #- MyCustomFilter
      - id: HelloService2
        #uri: http://localhost:8089/
        uri: lb://service2
        predicates:
        - Path=/helloservice2/**  
        
      #  filters:
      #  - CustomFilter
      
      - id: BookStoreProducerProject
        uri: lb://book-producer-service
        predicates:
        - Path=/bookstore/**  
        #filters:
        #- MyCustomFilter  
       
server:
  port: 9001
